'task:all':
  - "tasks/all/**"
'task:mpi':
  - "tasks/mpi/**"
'task:omp':
  - "tasks/omp/**"
'task:seq':
  - "tasks/seq/**"
'task:stl':
  - "tasks/stl/**"
'task:tbb':
  - "tasks/tbb/**"
ci:
  - ".github/**"
  - "appveyor.yml"
core:
  - "modules/core/**"
samples:
  - "modules/ref/**"
3rdparty:
  - "3rdparty/**"
infrastructure:
  - "*"
  - "!*/**"
  - "scripts/**"
  - "**/CMakeLists.txt"
docs:
  - "docs/**"
