if (ENABLE_ADDRESS_SANITIZER)
  if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    add_compile_options(-fsanitize=address)
    add_link_options(-fsanitize=address)
    message(STATUS "Enabled clang address sanitizer")
  else()
    message(WARNING "Address sanitizer is supported on clang compiler only! Switch your compiler to clang to enable it")
  endif()
endif()
