add_compile_definitions(PPC_PATH_TO_PROJECT="${CMAKE_CURRENT_SOURCE_DIR}")

MACRO(SUBDIRLIST result curdir)
    FILE(GLOB children RELATIVE ${curdir} ${curdir}/*)
    SET(dirlist "")
    FOREACH(child ${children})
        IF(IS_DIRECTORY ${curdir}/${child})
            LIST(APPEND dirlist ${child})
        ENDIF()
    ENDFOREACH()
    SET(${result} ${dirlist})
ENDMACRO()

option(USE_FUNC_TESTS OFF)
if( USE_FUNC_TESTS )
    message( STATUS "Enable functional tests" )
    add_compile_definitions(USE_FUNC_TESTS)
endif( USE_FUNC_TESTS )

option(USE_PERF_TESTS OFF)
if( USE_PERF_TESTS )
    message( STATUS "Enable performance tests" )
    add_compile_definitions(USE_PERF_TESTS)
endif( USE_PERF_TESTS )
