option(ENABLE_ADDRESS_SANITIZER OFF)
option(ENABLE_UB_SANITIZER OFF)
option(ENABLE_LEAK_SANITIZER OFF)
if(CMAKE_CXX_COMPILER_ID MATCHES "Clang" OR CMAKE_CXX_COMPILER_ID MATCHES "GNU")
  if(ENABLE_ADDRESS_SANITIZER)
    add_compile_options(-fsanitize=address)
    add_link_options(-fsanitize=address)
    message(STATUS "Enabled address sanitizer")
  endif()
  if(ENABLE_UB_SANITIZER)
    add_compile_options(-fsanitize=undefined
                        -fno-sanitize=signed-integer-overflow)
    add_link_options(-fsanitize=undefined -fno-sanitize=signed-integer-overflow)
    message(STATUS "Enabled UB sanitizer")
  endif()
  if(ENABLE_LEAK_SANITIZER)
    add_compile_options(-fsanitize=leak)
    add_link_options(-fsanitize=leak)
    message(STATUS "Enabled leak sanitizer")
  endif()
else()
  message(WARNING "Sanitizers are supported on gcc and clang compilers only!")
endif()
