name: 'Setup macOS Toolchain'
description: 'Configure Xcode, Homebrew packages, LLVM, OpenMP, OpenSSL, and ninja'
runs:
  using: 'composite'
  steps:
    - name: Install Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest-stable'
    - name: Setup environment
      shell: bash
      run: |
        brew update
        brew install ninja llvm libomp openssl
        brew link libomp --overwrite --force
