name: C++ Lint

on:
  workflow_call:
  push:
    paths:
      - '**/*.cpp'
      - '**/*.hpp'
      - '**/*.c'
      - '**/*.h'
      - '.clang-format'
      - '.github/workflows/cpp-lint.yml'
  pull_request:
    paths:
      - '**/*.cpp'
      - '**/*.hpp'
      - '**/*.c'
      - '**/*.h'
      - '.clang-format'
      - '.github/workflows/cpp-lint.yml'

jobs:
  clang-format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: DoozyX/clang-format-lint-action@v0.20
        with:
          source: '.'
          clangFormatVersion: 20
