on:
  workflow_call:

jobs:
  clang-format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: DoozyX/clang-format-lint-action@v0.20
        with:
          source: '.'
          clangFormatVersion: 20

  python-lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install flake8
        run: python3 -m pip install flake8
      - name: Run flake8
        run: python3 -m flake8 .

  shell-lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
      - name: Run shellcheck
        run: shellcheck scripts/*.sh
