name: macOS

on:
  workflow_call:
    inputs:
      ppc_tasks:
        description: 'Tasks to build'
        required: false
        type: string
        default: all

permissions:
  contents: read

jobs:
  clang-build:
    runs-on: macOS-26
    strategy:
      matrix:
        build_type: [Release, Debug]
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Setup macOS toolchain
        uses: ./.github/actions/setup-macos-toolchain
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ runner.os }}-clang
          create-symlink: true
          max-size: 1G
      - name: CMake configure
        run: >
          cmake -S . -B build -G Ninja
          -DCMAKE_C_FLAGS="-I$(brew --prefix)/opt/libomp/include"
          -DCMAKE_CXX_FLAGS="-I$(brew --prefix)/opt/libomp/include"
          -D CMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_INSTALL_PREFIX=install
          -D PPC_TASKS="${{ inputs.ppc_tasks }}"
      - name: Build project
        run: |
          cmake --build build --parallel -- --quiet
      - name: Install project
        run: |
          cmake --build build --target install -- --quiet
      - name: Archive installed package
        uses: ./.github/actions/archive-install
        with:
          path: install
          name: ${{ matrix.build_type == 'Debug' && 'macos-clang-debug-install' || 'macos-clang-install' }}
      - name: Show ccache stats
        run: ccache --show-stats
  clang-test:
    needs:
      - clang-build
    runs-on: macOS-26
    steps:
      - uses: actions/checkout@v7
      - name: Setup macOS toolchain
        uses: ./.github/actions/setup-macos-toolchain
      - name: Download installed package
        uses: ./.github/actions/download-install
        with:
          path: install
          name: macos-clang-install
      - name: Run func tests (MPI)
        run: scripts/run_tests.py --running-type="processes" --counts 1 2 3 4
        env:
          PPC_NUM_THREADS: 1
          PPC_TASK_MAX_TIME: 30
      - name: Run tests (threads)
        run: scripts/run_tests.py --running-type="threads" --counts 1 2 3 4
        env:
          PPC_NUM_PROC: 1
  clang-test-extended:
    needs:
      - clang-test
    runs-on: macOS-26
    steps:
      - uses: actions/checkout@v7
      - name: Setup macOS toolchain
        uses: ./.github/actions/setup-macos-toolchain
      - name: Download installed package
        uses: ./.github/actions/download-install
        with:
          path: install
          name: macos-clang-install
      - name: Run tests (threads extended)
        run: scripts/run_tests.py --running-type="threads" --counts 5 7 11 13
        env:
          PPC_NUM_PROC: 1
