name: Collect performance statistic

on:
  push:
  pull_request:
  schedule:
    - cron: '0 12 * * *'

jobs:
  ubuntu-gcc-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup environment
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install gcc-12 g++-12
        sudo apt-get install cppcheck ninja-build
        sudo apt-get install mpich libmpich* mpi* openmpi-bin
        sudo apt-get install libomp-dev
        sudo apt-get install valgrind
        python3 -m pip install xlsxwriter
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
          key: ${{ github.job }}
          create-symlink: true
    - name: CMake configure
      run: >
        cmake -S . -B build
        -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache
        -G Ninja -D USE_SEQ=ON -D USE_MPI=ON -D USE_OMP=ON -D USE_TBB=ON -D USE_STL=ON
        -D USE_FUNC_TESTS=ON -D USE_PERF_TESTS=ON
        -D CMAKE_BUILD_TYPE=RELEASE
      env:
        CC: gcc-12
        CXX: g++-12
    - name: Ninja build
      run: |
        cmake --build build
      env:
        CC: gcc-12
        CXX: g++-12
    - name: Run perf tests
      run: |
        source scripts/generate_perf_results.sh
    - name: Archive results
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r perf-stat.zip build/perf_stat_dir
    - name: Upload results
      uses: actions/upload-artifact@v4.3.0
      with:
        name: perf-stat
        path: perf-stat.zip
