name: Performance

on:
  workflow_call:

permissions:
  contents: read
  packages: read

jobs:
  ubuntu-gcc-build-perf-stats:
    runs-on: ubuntu-26.04
    container:
      image: ghcr.io/learning-process/ppc-ubuntu:1.3
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup environment
        run: |
          python3 -m pip install -r requirements.txt --break-system-packages --ignore-installed
      - name: Download installed package
        uses: ./.github/actions/download-install
        with:
          path: install
          name: ubuntu-gcc-install-ubuntu-26.04
      - name: Run perf tests
        run: |
          scripts/run_tests.py --running-type=performance
        env:
          PPC_NUM_PROC: 2
          PPC_NUM_THREADS: 2
          OMPI_ALLOW_RUN_AS_ROOT: 1
          OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
      - name: Archive results
        working-directory: build
        run: zip -r ../perf-stat.zip perf_stat_dir
      - name: Upload results
        uses: actions/upload-artifact@v7
        with:
          name: perf-stat
          path: perf-stat.zip
  macos-clang-build-perf-stats:
    runs-on: macOS-26
    steps:
      - uses: actions/checkout@v6
      - name: Setup macOS toolchain
        uses: ./.github/actions/setup-macos-toolchain
      - name: Setup environment
        run: |
          python3 -m pip install -r requirements.txt --break-system-packages
      - name: Download installed package
        uses: ./.github/actions/download-install
        with:
          path: install
          name: macos-clang-install
      - name: Run perf tests
        run: |
          scripts/run_tests.py --running-type=performance
        env:
          PPC_NUM_PROC: 1
          PPC_NUM_THREADS: 2
      - name: Archive results
        working-directory: build
        run: zip -r perf-stat-macos.zip perf_stat_dir
      - name: Upload results
        uses: actions/upload-artifact@v7
        with:
          name: perf-stat-macos
          path: perf-stat-macos.zip
