name: Python Lint

on:
  workflow_call:
  push:
    paths:
      - '**/*.py'
      - '**/*.sh'
      - 'setup.cfg'
      - '.github/workflows/python-lint.yml'
  pull_request:
    paths:
      - '**/*.py'
      - '**/*.sh'
      - 'setup.cfg'
      - '.github/workflows/python-lint.yml'

jobs:
  python-lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install flake8
        run: python3 -m pip install flake8
      - name: Run flake8
        run: python3 -m flake8 .

  shell-lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
      - name: Run shellcheck
        run: shellcheck scripts/*.sh
